openai_api_key = "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"
scraperapi_key = "7933bcd7a02c94929acb0d0a0405099f"
